---
title: 'Biometric Scans at Airports: Where is the Bottleneck?'
date: '2019-12-13'
author: Nick Arnosti
tags:
  Airlines
categories:
  Operations
---

In the past year, Delta has rolled out [biometric boarding](https://news.delta.com/delta-expands-optional-facial-recognition-boarding-new-airports-more-customers) for international flights from Atlanta, Salt Lake City, and my home airport of Minneapolis/Saint Paul. The idea is that rather than having to repeatedly scan your boarding pass and passport, facial recognition software will identify you.^[You may have an instinctive reaction to this proposal, which sounds like it comes from a dystopian novel. There are interesting privacy-related questions one could discuss, but that's not what this post is about.] Delta claims that this can reduce the time to scan each passenger by several seconds, shaving up to 9 minutes from the boarding process.

I believe that biometric scans can process passengers more quickly, but am skeptical that this will result in faster boarding.^[I should note that this post was inspired by a [similar one by Kathi Kellenberger](https://www.red-gate.com/simple-talk/opinion/editorials/wheres-the-bottleneck/).] In my experience, the gate agent is rarely, if ever, the bottleneck. Instead, I am scanned promptly and then wait patiently on the jetbridge as passengers ahead of me go through the slow process of storing their luggage and taking their seat. Sometimes, the gate agent must even stop scanning, because there is no more room for passengers on the jetbridge. As we teach in Operations, if you haven't addressed the bottleneck, you haven't really made the process faster. See [this post](/Blog/seatpitch) for another example of bottlenecks in the aviation industry.

One important consideration is how departure time is calculated. I've heard it said that a flight is considered to have departed once the gate is closed. If this is the case,^[I haven't verified that this is the official definition, but will assume it is to make my point.] then as long as Delta has long jetbridges, they would be able to jam passengers onto them and close the gate earlier. This could result in better on-time performance, despite the fact that pushback times and arrival times would presumably not be altered. This is an example of [Goodhart's Law](https://en.wikipedia.org/wiki/Goodhart%27s_law#:~:targetText=Goodhart's%20law%20is%20an%20adage,actions%20that%20alter%20its%20outcome.), which points out that any measurement that is used will distort behavior.

