---
title: 'How Can You Move Back on a Waiting List?'
date: '2020-05-18'
author: Nick Arnosti
tags:
  School Choice
categories:
  Market Design
---

#Changes to School Admissions in NYC

New York has made some recent changes to their middle and high school admissions process. Previously, all students would submit preference lists, which were processed using a variant of the Deferred Acceptance algorithm. Students who were not admitted to any school on their list^[Typically, this accounts for approximately 7\% of the 80,000 students apply to high school.] could apply to schools with vacancies in a second round. In addition, those who were unhappy with their assignment could participate in an opaque appeals process.

Last year, the DOE decided to give _every_ student an assignment: those who didn't get into any of their listed schools were administratively assigned to a nearby option. This year, they decided to do away with the second round (and the appeals process) entirely. Instead, students are automatically placed on a waitlist for each school that they ranked above their assigned school. They are informed of their position on the list, and able to see it update in real time. The DOE claims that this will make the process simpler for parents (who don't have to appeal or apply multiple times), as well as more transparent.

In theory, I support this change, but the devil is always in the details. At the time the change was announced, [Al Roth raised several unanswered questions](https://marketdesigner.blogspot.com/2019/08/waitlists-in-nyc-school-choice-early.html), as did [some parents](https://newyorkschooltalk.org/2019/08/10-questions-about-nycs-newest-high-school-admissions-plan/). Admissions outcomes [came out in March](https://insideschools.org/news-&-views/nyc-8th-graders-get-high-school-admissions-results), and now we're starting to see [how the waitlists work](https://ny.chalkbeat.org/2020/5/8/21252547/nyc-high-school-admissions-waitlist-confusion).

#Several Concerns

The new process seems to create a lot of [extra work for principals](https://ny.chalkbeat.org/2020/3/18/21196052/nyc-high-school-offers-are-coming-this-week-with-a-big-change-waitlists-here-s-what-you-should-know), who are in charge of fielding inquiries from parents whose children have been waitlisted, and notifying parents if their children are admitted off the waitlit.^[This is at least partially offset by the fact that they no longer need to do recruitment for the second round.] This can be especially burdensome because one vacancy can create a chain of waitlist admissions: a spot opens up at School A, and is filled by a student who leaves a vacancy at School B, which is filled by a student who leaves a vacancy at School C, and so on. Because students have a week to accept their position, this process could stretch well into the fall. This increases uncertainty for both students and schools.

In fact, there are ways to organize the waitlists that minimize this "churn." [Itai Feigenbaum](https://www.gc.cuny.edu/Page-Elements/Academics-Research-Centers-Initiatives/Doctoral-Programs/Computer-Science/Faculty-Bios/Itai-Feigenbaum), [Yash Kanoria](http://www.columbia.edu/~yk2577/), [Irene Lo](https://sites.google.com/view/irene-lo), and [Jay Sethuraman](http://www.columbia.edu/~js1353/) have [a nice paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2993375) on this topic. In their model, students may not accept a school that they initially listed -- for example, because they accept an offer from a school that did not participate in the matching process.^[In New York, private schools (unsurprisingly) don't participate in the centralized process. Perhaps more surprisingly, neither do charter schools and 9 selective specialized high schools.] 

That paper assumes that student preferences are "consistent," meaning that a student will never join the waitlist for a school that they did not list, or listed below their assigned school. In practice, it seems that [both of these behaviors occur](https://ny.chalkbeat.org/2020/5/8/21252547/nyc-high-school-admissions-waitlist-confusion) (though it's not clear to me how frequently). If a student who joins the waitlist has high priority for that school, it moves others _backwards_ on the list, causing confusion and frustration. 

#Possible Solutions

If we take as given that a student should never see their waitlist number get worse, several "solutions" come to mind.

One possibility is to stop telling students their position on the waitlist. This is the approach taken by many housing authorities in the US. This would be an "easy" change, as it doesn't require modifications to how waitlists are handled on the back end. However, if one of the goals of introducing waitlists was transparency, then this seems like a step backwards.^[The DOE could also provide partial information -- something like green = "good chance of admission", yellow = "some chance of admission", red = "very low chance of admission." However, this requires forecasting movement on each waitlist. Additionally being told you're in a "green" position could seem almost like a promise of future admission, causing more dissatisfaction if this does not occur.]

A second possibility is to always place students who add themselves to the waitlist below those who were automatically added. This would be more in line with a traditional waitlist, and would imply that students would never see their waitlist number increase.^[Adding students to the bottom of the list in first come, first served order might be perceived as unfairly rewarding those who are savvy and have reliable internet access. To avoid this, the DOE could batch applicants from each week, and assign waitlist numbers within each batch based on the school's priorities.] To me, it seems reasonable to say that priority on the waitlist is not necessarily identical to the priorities used to determine the initial assignment.^[Apparently I am not the only one: the aforementioned paper by Feigenbaum et al. reduces churn by using different priority orders in each stage.]

One concern is that there might be students who would normally be guaranteed a spot at their local school. Telling them that they cannot be admitted because they did not list this school on their initial application could prove problematic. Thus, perhaps we could consider a hybrid of the current system and the second approach above. Students who are "guaranteed" a spot are admitted straight away, and never added to the waitlist. Students who merely would have had "priority" for that spot are placed at the back of the list. This would guarantee that waitlist positions never worsen, while accommodating certain commitments (i.e. that you can always attend your neighborhood school).


#Conclusion

This seems like a tricky problem, and I'm not sure there is a great solution. In part, the right approach depends on how seriously we take the existing priorities: are they to be viewed as legitimate preferences of the city or school, or merely a way to decide among students? If the latter, then using different priorities for waitlists (i.e. prioritizing those who listed the school in their initial application) seems reasonable. 

If the priorities are truly important, then one could argue that the current approach is reasonable, and simply needs to be explained more clearly to parents. This is the approach adopted for organ transplantation. There, it is possible to move backwards on the waitlist: an urgently sick patient may jump ahead of a less sick one, even if the latter has waited for longer. For school choice, it is less clear that the priorities are truly important, and I think it will always be difficult to convince parents that a waitlist where other students can jump ahead of your child is transparent and fair.

Do you think it is reasonable to prioritize those who listed a school on their initial application? Do you have other ideas for how this process could be handled? Leave a comment below!
