---
title: 'How Valuable is an Offensive Rebound?'
date: '2019-12-15'
author: Nick Arnosti
draft:
tags:
categories:
  Sports
---

#Motivation

This fall, I started playing basketball with other junior faculty members. Most of them are better shooters than I am, but I have one key advantage: I am 6'2". As a result, a big part of my contribution is to grab as many rebounds as possible. Today's post tries to quantify the value of this skill. I started with two key questions: 

1. How valuable is offensive rebounding skill, relative to shot-making?
2. Does the answer to the first question depend on whether you're playing NBA rules (after scoring, you play defense) or pickup rules (after scoring, you stay on offense)?

#Model

I wrote down what I imagine to be the simplest possible model addressing this question. Let's assume that there are no turnovers, so the ball changes hands only after a shot. Each shot goes in with probability $p$, and the probability of an offensive rebound is $\alpha$. Let's deviate from standard terminology and call a "possession" everything that happens until the opposing team receives the ball (i.e. if my team takes three consecutive shots, they are all one possession). Furthermore, I will adopt pickup scoring conventions, where each basket simply counts as one point. As a function of $p$ and $\alpha$, how many points per possession can you expect to score?

Under pickup rules, the possession only ends if we miss and do not grab the offensive rebound, which occurs with probability $(1-p)(1-\alpha)$. Thus, the number of shots per possession follows a geometric distribution with termination probability $(1-p)(1-\alpha)$, so the average number of shots per possession is $\frac{1}{(1-p)(1-\alpha)}$. Because each shot goes in with probability $p$, the average number of points scored per possession is $$V^{Pickup}(p,\alpha) = \frac{p}{(1-p)(1-\alpha)}.$$

What about under NBA rules? In this case, each shot ends the possession with probability $p + (1-p)(1-\alpha)$, so by the same logic above, the expected number of points scored per possession is now $$V^{NBA}(p,\alpha) = \frac{p}{p+(1-p)(1-\alpha)}.$$ 
Intuitively, inspection of the formulas reveals that this is lower than under pickup rules.

#Analysis

We now turn to the two questions above. First, what is the value of offensive rebounding? 

You might measure this by looking at the increase in points per possession as a result of an increase in offensive rebounding rate.^[We could look at the absolute difference (study $\frac{d}{d\alpha}V(p,\alpha))$), or as a percentage increase (study $\frac{d}{d\alpha}\log(V(p,\alpha))$). In either case, an increase in offensive rebounding rate has a bigger effect under pickup rules. At the extreme, as $\alpha \rightarrow 1$, points per possession increase without bound under pickup rules, whereas they remain below $1$ under NBA rules.] However, this doesn't directly address the _relative_ value of shot-making and offensive rebounds.

To do this, we can compare two teams, one of which (team 'Dan') has a higher shooting percentage than the other (team 'Nick'). We can ask, 'How much higher does team Nick's offensive rebounding have to be, in order to have the same points per possession?' Let's start assuming NBA scoring. Suppose that Dan makes 1/3 of his shots, but never graps an offensive rebound.^[This is unfair to my colleague Dan, who does in fact grab his fair share of rebounds, but I want to keep the math simple.] Thus, on average he scores 1/3 of a point per possession. Nick makes only 20% of his shots. What must his offensive rebounding rate be to match Dan's 1/3 points per possession? The answer is 50%.

We can carry out this exercise for varying $p$ and $\alpha$. Figure \@ref(fig:bball) displays curves of equivalent teams. The red curve corresponds to teams that score $1/3$ of a basket per possession, and includes both team Dan at (1/3,0) and team Nick at (1/5,1/2).

```{r bball,echo=TRUE,fig.cap = 'Each curve identifies teams with the same points per possession (x-intercept).'}
alphaNBA = function(p,v){return(1-p/(1-p)*(1/v-1))}
V = c(1:5)/6
plot(NULL,xlim=c(0,1),ylim=c(0,1), xlab='Shooting Percentage',ylab='Offensive Rebounding Rate',las=1,xaxs='i',yaxs='i',xaxt='n')
axis(1,at=c(0:6)/6,labels=c('0','1/6','2/6','3/6','4/6','5/6','1'))
for(v in V){ plot(Vectorize(function(p){return(alphaNBA(p,v))}),add=TRUE) }
plot(Vectorize(function(p){return(alphaNBA(p,1/3))}),col='red',add=TRUE)
```

Overall, my reaction is that these curves are disappointingly steep. That is, it takes a large increase in offensive rebounding proficiency to offset a small decline in shooting percentage.^[I console myself by noting that teams are composed of individuals. For a team with a good shooter, it may be more valuable to add a good rebounder than another shooter. But a team of all rebounders isn't going to fare well.] Perhaps under pickup rules, the value of rebounding is higher? After all, if you grab a rebound, you are potentially giving your team a series of baskets, instead of one.

We can tackle this question by asking which team above (Dan or Nick) scores more points per possession under pickup rules. Recal that they were equal under NBA rules, at 1/3 of a point per possession. If team Nick scores more than team Dan under pickup rules, we can conclude that offensive rebounding is more valuable under pickup rules.

Crunching the numbers, we see that under pickup rules, both teams expect to score 0.5 points per possession! I initially found this surprising -- did I just happen to choose special numbers? Turns out, the answer is 'no.' We can see this by inverting our expressions above to get "possessions per point." We see that this is $(1-p)(1-\alpha)/p$ under NBA rules, and $(1 -p)(1-\alpha)/p + 1$ under pickup rules. This immediately implies the following result, which I interpret to mean that the rule set (pickup vs NBA) doesn't really affect the relative value of the two skills. 

> **Proposition**. Consider team $A$, with shooting percentage $p$ and offensive rebounding rate $\alpha$, and team $B$ with shooting percentage $p'$ and offensive rebounding rate $\alpha'$. If $A$ scores more points per possession than $B$ under pickup rules, then the same is true under NBA rules (and vice versa).

Of course, shooting is a skill that doesn't necessarily translate to defense, whereas good offensive rebounders are presumably also good defensive rebounders. The reasoning above could also be used to quantify the value of good on-ball defense (lowering the opponent's $p$) and good defensive rebounding (lowering their $\alpha$). However, at this point I think my time would be better spent working on my shot at the gym, rather than working through math trying to justify my value to the team. 