---
title: 'Why You Should Bet on Favorites'
date: '2019-12-03'
author: Nick Arnosti
tags:
  Gambling
categories:
  Sports
---

Today's post is about a topic that caught my eye during my first year of graduate school: inferring win probabilities from betting lines. It is an empirical fact that conventional betting line estimates systematically understate the favorite's chance of winning. Traditional explainations argue that bettors are irrational. This post points out that the bias could appear even with rational bettors, due to the fact that bookies set the odds to minimize their exposure.^[There is a huge literature on the favorite longshot bias (this is one reason I decided to stop thinking about it). Several papers attempt to empirically distinguish between explanations. I believe that behavioral considerations may play a role, and therefore view this post as an introduction to an alternative explanation, rather than an attempt to "refute" other explanations.] Because I attended the Packers-Giants football game on Sunday, I will use that game as a running example.




## Inferring Win Probabilities from Betting Lines

Suppose that someone offers you the following contract: you pay them $p$ up front, and they will pay you \$1 if the Packers defeat the Giants. If you are risk neutral and believe the Packers' chance of winning is $q$, the contract is favorable if $p < q$, and fair if $p = q$. Therefore, we might interpret the contract price $p$ as an estimate of the win probability $q$. Last week it cost about \$0.76 to place a bet that would pay \$1 if the Packers defeated the Giants,^[In this post, I translate all bets into the language of "bet $p$ for a \$1 payout." Betting lines are traditionally reported in more complex ways. For example, the Money Line for the Packers-Giants game was Packers -310, Giants +255. A negative number indicates that the team is favored: a line of -310 means that you must bet \$310 to earn \$100 in profit (a total payoff of \$410) if the Packers win, implying a price of $\frac{310}{310 + 100} \approx 0.76$ to potentially win a dollar. Positive lines are used for underdogs: a line of +255 means that you earn \$255 in profit for each \$100 that you bet, implying that it costs $\frac{100}{255+100} \approx 0.28$ to potentially win a dollar. In other contexts (such as picking a team to win the Super Bowl) odds like 4-1 are used. This means that a \$1 bet could earn \$4 in profit (\$5 total). In other words, it costs \$0.20 to win \$1.] so we might estimate that the Packers had a 76\% chance of winning.

## Accounting for the Bookie's Cut

This estimate can be refined by accounting for the fact that bookmakers are trying to make a profit. For example, it cost about \$0.28 to place a bet that would pay \$1 if the Giants won, and it clearly can't be the case that the Packers have a 76\% chance of winning and the Giants have a 28\% chance. The apparent contradiction arises because the bookie wants a cut of the action. We can estimate the size of this cut by asking "How much would it cost to guarantee a \$1 payout?" If the bookie took no cut, the answer would be \$1. For the Packers-Giants game, you had to pay \$0.76+\$0.28 = \$1.04.^[A cut of less than 4% is fairly modest, and many bets have much larger cuts. For example, at the current [Super Bowl Odds](https://www.vegasinsider.com/nfl/odds/futures/), it would cost \$1.25 to guarantee a dollar (see code below). I've noticed that this holds generally: cuts are larger for binary outcomes than outcomes with many options. This might be because the bookie faces higher risk in the latter case. More cynically, it might be because when there are many possible outcomes, bettors have a harder time determining the cut. ``` odds=c(3,4,4,8,8,10,14,16,20,40,40,80,80,100,100,200,200,300,500,rep(5000,3),rep(10000,4)) sum(c(1/(1+odds))) #Cost of ensuring a $1 payout```.] We can refine our estimated win probability by dividing the cost of the Packers bet by the total cost: $0.76/1.04 \approx 0.73$.^[One way of thinking about this is that at the current prices, a bettor who is determined to spend their budget will prefer to bet on the Packers if their belief is $q > 0.73$, and on the Giants otherwise.]


## The Favorite Longshot Bias 

The theory that betting odds provide unbiased win probability estimates can easily be tested. In cases where the favorite is predicted to win with probability 73\%, how often do they actually win? Many such studies have been conducted, and they all find that the favorites win more often than predicted.

This effect, dubbed the "favorite longshot bias", was first observed in betting on horse races. In 1981, a [paper](https://pubsonline.informs.org/doi/10.1287/mnsc.27.12.1435) in Management Science argued that it is possible to make money by betting on favorites, despite the track's large cut. The claim that favorites are better bets than longshots has also been demonstrated in British [running races](https://www.jstor.org/stable/2235276?seq=1#metadata_info_tab_contents) and [soccer matches](https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-9485.00151), American [college basketball and football](https://www.sciencedirect.com/science/article/pii/S1062976916000041), and [tennis](https://www.tandfonline.com/doi/full/10.1080/13504851.2013.842628).


## Explanations

People have spent a lot of time trying to explain _why_ the favorite longshot bias exists: see [Ottaviani and Sorensen (2008)](https://www.sciencedirect.com/science/article/pii/B9780444507440500093) for a survey. The most common explanations relate to bettor psychology: they argue that bettors underestimate small probabilities, or are seeking excitement and are therefore risk-seeking. In this post, I will focus on a different explanation, first offered by [Ali (1977)](https://www.journals.uchicago.edu/doi/pdfplus/10.1086/260600). This explanation focuses on how bookies set the odds, rather than how gamblers react to them.

Let's write down a model. Each bettor has a gambling budget, and a subjective belief about the chance that the Packers will win. Subjective beliefs are drawn from a distribution that is centered at the Packers' true win probability, and are independent from the gambling budget. Bettors use their subjective win probabilities to decide which bets to place.^[Importantly, the model assumes that learning the odds doesn't influence how people bet. This could mean that they don't update at all, or could simply mean that a person with initial belief of 60% who sees a price of $0.80 never updates their beliefs to be above 80%.]

For example, suppose the Packers had an 80% chance of beating the Giants on Sunday. If the bookie sets odds to reflect this probability, everyone who believes the Packers have a greater than 80% chance will bet on them, with the remainder betting on the Giants. Because beliefs are centered at 80%, similar volumes should be bet on both teams. This betting pattern turns the bookie into a Packers fan for the day. If the Packers win, Packers backers get a modest payoff, and the bookie makes money. If the Giants win, their backers get much more, and the bookie loses money.^[To put numbers on this, assume that 100 bettors bet $1 each, with 50 betting on each team, and assume that the bookie takes no cut. This implies that Packers backers get $1.25 back if they win, whereas Giants backers will be paid $5 if correct. If the Packers win, the bookie pays out $62.50, earning $37.50 in profit. However, if the Giants win, the bookie pays out $250, incurring a net loss of $150.] 

The bookie might not like being exposed to such risk. Instead of setting the odds so that the same amount of money is bet on each team, most bookies try to set the odds so that their _exposure_ (the amount of money they have to pay out) is the same for each outcome.^[In most betting markets, it isn't possible to perfectly predict the price that will equalize bets on the two sides, and bookies gradually adjust prices as bets are placed. Bets on horse races run on a "parimutuel" system, in which the bookie's profit is defined to be identical for all outcomes. In this system, bettors place bets without knowing the precise odds. After bets are placed, the bookie takes a cut (usually around 20\%), and distributes the remainder to winning bettors. This system seems amazing for the bookies, and I'm honestly not sure how they get away with it.] To achieve this, the bookie wants most people to bet on the Packers, and therefore must set the odds to make a bet on the Packers more attractive. As a result, implied win probabilities understate the Packers' chance of winning.^[To be precise, if beliefs are drawn from distribution $F$ centered at $p = F^{-1}(1/2)$, then the bookie sets price $\hat{p}$ satisfying $\frac{1 - F(\hat{p})}{\hat{p}} = \frac{F(\hat{p})}{(1-\hat{p})}$. It is straightforward to show that this has a unique solution for any $F$, and that $\hat{p}$ is in between $p$ and $0.5$.]

## Conclusions

There appears to be a large bias in most betting markets, whereby bets on favorites are much more profitable than bets on longshots. In some cases, bets on favorites may be literally profitable, despite large cuts taken by the bookie. In part, this bias comes from the fact that bookies manage their exposure, and want fewer bets placed on longshots than on favorites. 

I'm not endorsing sports betting (in fact, I have only placed bets on the one night of my life that I visited Las Vegas), but if you're determined to bet, go with the favorite.
