---
title: 'What do Toilet Paper and License Plates Have in Common?'
date: '2020-04-12'
author: Nick Arnosti
tags:
  Public Policy
categories:
  Market Design
---


My research usually starts from the premise that there is a shortage of some item, which triggers the need for an allocation policy. However, sometimes the allocation policy can _cause_ a shortage -- especially in the presence of uncertainty. This, in turn, results in an inefficient allocation.

For one topical example, consider toilet paper. In normal times, people have confidence that they will be able to buy toilet paper whenever they need it. As a result, they wait until they run low to buy more. This behavior helps to ensure that toilet paper is always in stock. However, there is also a bad equilibrium, in which people believe that the store might not have toilet paper when they need it. Because the prospect of going without toilet paper is unappealing, they buy extra when they can. This creates a self-fulfilling prophecy: stores frequently run out, justifying the behavior of hoarding. Some people end up with too much toilet paper, and others with too little.

Today, I'll discuss this idea in the context of Beijing's license plate lotteries.


##Background

Many major cities in China [ration the supply of new license plates](https://www.wsj.com/articles/more-license-plates-wont-turbocharge-chinas-car-market-11559555116). In Shanghai, these are allocated by auction, with [recent winners paying the equivalent of more than \$12,000](https://www.economist.com/china/2018/04/19/why-a-licence-plate-costs-more-than-a-car-in-shanghai). In Beijing, applicants must choose between applying for a traditional gas-burning vehicle and a "New Energy Vehicle" (NEV). License plates for traditional vehicle are awarded in semi-monthly lotteries, while the those for NEVs are allocated on a first-come, first-served basis. The lottery for traditional vehicles has become increasingly congested as quotas are reduced^[Before the lottery was implemented in 2011, over 700,000 new licenses were issued each year. In the first year of the lottery, 240,000 licenses were awarded, but this year the quota for gas vehicles is 40,000.] and applications soar: recent lotteries have had [2,000 applicants for every winner selected](https://www.chinadailyhk.com/articles/45/138/47/1530074750586.html).^[My understanding is that the lottery is not done uniformly at random: applicants who have applied repeatedly are given higher odds than newcomers. This is remniscent of [bonus point systems for hunting licenses](https://www.themeateater.com/hunt/big-game/big-game-tags-understanding-license-draws). I ignore this feature in the analysis that follows. Incorporating it would only increase the incentive for people to begin applying before they need a car.] Although NEVs were initially unpopular, demand has surged, and the length of the waiting list is now [nine times the annual quota](https://www.chinadaily.com.cn/a/201908/25/WS5d6234c3a310cf3e35567b91.html).

When the lottery was first announced, it triggered a [rush to buy cars](https://www.latimes.com/world/la-xpm-2011-jan-24-la-fg-china-cars-20110124-story.html) before the policy was enacted. As the odds of winning continue to decline, ever more people decide to apply -- even those who do not currently need a car!^[A similar phenomenon arises with housing in some European cities, where wait lists can take decades to clear, resulting in people rushing to put their name down as soon as they are eligible.] 

##Model

Time is discrete. In each period, a unit mass of agents arrives. Each agent lives for two periods. In the first period (college), they have no need for a car. In the second, their value for car ownership varies, with $\bar{F}(v)$ giving the fraction with value above $v$. Agents only learn their value for a car in the second period. The cost of car ownership is $c$. Absent any quota, we would expect people to wait until they graduate, and then buy a car if $v > c$. In this case the number of cars purchased in each period is $\bar{F}(c)$.

The government decides to use a lottery to implement a quota $q$ on car sales. In each period, anyone who wishes to buy a car may apply for free. If the number of applicants is below $q$, all are permitted to buy a car. Otherwise, a quantity $q$ are selected uniformly at random.

##Analysis

Let us study how agents respond to this system. Anyone who does not get a car in the first period have a simple strategy in the second: apply if and only if $v > c$. Thus, the real question is whether to apply for a car in the first period, _before_ knowing whether you will need it.

If you believe that you will be able to get a car whenever you want one, then it obviously makes sense to wait. However, if you are concerned that a car will not be available in the future, then you might try to buy one now, despite the risk that you might not need it. In general, waiting is the best strategy if the probability of winning the lottery is above some threshold $\bar{p}$;^[The quantity $\bar{p}$ depends on the value distribution $F$ and the cost of ownership $c$. I leave the exact expression for $\bar{p}$ as an exercise for the reader.] otherwise, applying early is superior.

If all agents adopt the "wait" strategy, then the mass of agents entering in each lottery is $\bar{F}(c)$, and the probability of success is $$p_W = \min\left( \frac{q}{\bar{F}(c)},1\right).$$

If all agents adopt the "early" strategy, then we wish to solve for the resulting probability of winning each lottery $p_E$. The mass of lottery entrants in each period is $1 + (1-p_E) \bar{F}(c)$, so the win probability must solve $$p_E (1 + (1-p_E) \bar{F}(c)) = q.$$

We now search for an equilibrium. It is easy to show that there is always at least one equilibrium. When the quota $q$ is sufficiently large, the only equilibrium is for all agents to wait; when $q$ is sufficiently small, the only equilibrium is for all agents to apply early. However, for a wide range of quotas, both of these strategies may be equilibria. In fact, this can arise even if $q > \bar{F}(c)$, meaning that it's possible to give a car to everyone who will want one!

##Conclusions

When lottery odds are low and people apply before they need a car, there are significant welfare consequences: many people win cars that they never need, while others lose repeatedly and never get a car (despite wanting one). Although the former group would like to sell their license to the latter, transfering a license plate is [not permitted](https://qz.com/153742/the-genius-ways-beijing-drivers-get-around-the-citys-license-plate-lottery/), except to a spouse.^[However, there is a [black market](https://bfi.uchicago.edu/wp-content/uploads/BFI_WP_2019139.pdf), as well as [sham marriages](https://www.thedrive.com/news/31231/beijing-drivers-are-entering-sham-marriages-just-to-get-their-cars-registered) to enable license transfer.] There are other contexts in which scarcity results in an inefficient allocation: my [paper with Peng Shi](/ResearchPapers/Arnosti-Shi_AffordableHousing.pdf) points out that when odds in housing lotteries are low, people will apply everywhere, resulting in an inefficient matching of people to apartnments.

One interesting caveat to the analysis above is that the entire purpose of this particular quota is to limit externalities from driving. Although awarding license plates to people who don't need cars seems inefficient, it does have the benefit that these people likely won't drive as much. For a more complete analysis of this effect, see [this paper](http://www.restud.com/wp-content/uploads/2017/11/beijing_lottery_2017_Final.pdf). Another consideration, is that reducing the number of licensed cars may change the [fleet composition](https://felixmunozgarcia.files.wordpress.com/2017/09/a-less-efficient-fleet-unintended-consequences-of-beijings-vehicle-lottery-system.pdf) or driving behavior, thereby [reducing emissions less than intended](https://www.researchgate.net/publication/264350212_A_review_of_Beijings_vehicle_registration_lottery_Short-term_effects_on_vehicle_growth_and_fuel_consumption).

