---
title: 'Should Government Programs be Means-Tested?'
date: '2020-01-07'
author: Nick Arnosti
draft:
tags:
  
categories:
  Miscellaneous
---

Today, we'll address a question that comes up frequently in policy discussions: whether government programs should be means-tested. For example, should a "basic income" program be available to all, or only those making below a certain income level? Similarly, one might ask whether it should be paid for by taxes on all, or only on the rich. This post raises a simple but important point, and is largely copied from [Greg Mankiw](https://scholar.harvard.edu/files/mankiw/files/how_to_increase_taxes_on_the_rich.pdf). To make our question concrete, let's compare the following basic income policies: 

**Policy A**: a universal basic income of \$1,000/month, paid for with a flat tax of 20% on income.

**Policy B**: a means-tested transfer of \$1,000 per month aimed at the truly needy. The full
amount goes to those with zero income. The transfer is phased out: recipients lose 20 cents of it for every dollar of income they earn. These transfers are financed by a progressive income tax: The government taxes 20 percent on all income above $60,000 per year

The latter policy seems much more progressive: it gives the largest transfer to those with the lowest incomes, and only taxes those with high incomes. In fact, the two policies are mathematically equivalent: the net transfer is identical for every income level! We can see this in Figure \@ref(fig:equivalence) (code included below). This shows that the discussion of who benefits and who pays for policies can be very misleading.


```{r equivalence,echo=TRUE,fig.cap = 'Two proposed policies. Taxes paid in red, benefits received in black. The policy on the left has universal benefits funded by a flat tax, while the one on the right has progressive taxes and benefits. However, the combined effect of the two policies (dashed lines) is identical.',fig.show = "hold", out.width = "50%"}

flat_tax = Vectorize(function(x){return(.2*x)})
universal_income = Vectorize(function(x){return(-12)})

progressive_tax = Vectorize(function(x){return(0.2*max(x-60,0))})
meanstested_income = Vectorize(function(x){return(-.2*max(60-x,0))})

plot(flat_tax,xlim=c(0,140),ylim=c(-15,30),las=1,ylab='',xlab='Income',xaxs='i',yaxs='i',col='red')
plot(universal_income,xlim=c(0,140),add=TRUE)
plot(function(x){return(flat_tax(x)+universal_income(x))},xlim=c(0,140),add=TRUE,lwd=2,lty='dashed')


plot(progressive_tax,xlim=c(0,140),ylim=c(-15,30),las=1,ylab='',xlab='Income',col='red')
plot(meanstested_income,xlim=c(0,140),add=TRUE)
plot(function(x){progressive_tax(x)+meanstested_income(x)},xlim=c(0,140),add=TRUE,lwd=2,lty='dashed')

```


To me, this suggests that there are advantages to making benefits universal, rather than means-tested. One reason (often raised by those on the right) is that this avoids the overhead of setting up offices to verify eligibility. Another (which may appeal to those on the left) is that this will ensure that benefits are awarded fairly, rather than being granted inconsistently by potentially biased administrators.^[One could argue that if people must "prove" their eligibility, only those who really need benefits will claim them, so support will be more effectively targeted to the needy. I'm concerned, however, that in many cases those who claim benefits are those who are best informed or have been guided through the process, rather than those most in need.] Additionally, on the messaging side, universality may make the policy more popular, and reduce stigma against the beneficiaries. For example, there is a lot of stigma against welfare recipients, but social security is [very popular](https://socialsecurityworks.org/2019/03/26/social-security-polling/) and not stigmatized.

What other factors should we consider when choosing between a means-tested program and a universal one? Give me your thoughts below!


