<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="2113.6">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Times; color: #000000; -webkit-text-stroke: #000000}
    p.p4 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Times; color: #000000; -webkit-text-stroke: #000000; background-color: #000000; background-color: rgba(0, 0, 0, 0); min-height: 14.0px}
    p.p5 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Times; color: #000000; -webkit-text-stroke: #b80e3d; background-color: #000000; background-color: rgba(0, 0, 0, 0)}
    span.s1 {font-kerning: none}
  </style>
</head>
<body>
<p class="p1"><span class="s1"><!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Survivorship Bias when Assessing Allocation Policies | b</title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/fonts.css" />
    <script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  </head>

  <body>
    <nav>
    <ul class="menu">
      
      <li><a href="/">Home</a></li>
      
      <li><a href="/research/">Research</a></li>
      
      <li><a href="/teaching/">Teaching</a></li>
      
      <li><a href="/blog/">Blog</a></li>
      
    </ul>
    <hr/>
    </nav>
</span></p>
<h1 style="margin: 0.0px 0.0px 16.1px 0.0px; font: 24.0px Times; color: #000000; -webkit-text-stroke: #000000"><span class="s1"><b>Survivorship Bias when Assessing Allocation Policies</b></span></h1>
<p class="p1"><span class="s1"></span></p>
<h2 style="margin: 0.0px 0.0px 14.9px 0.0px; font: 18.0px Times; color: #000000; -webkit-text-stroke: #000000"><span class="s1"><b>Nick Arnosti</b></span></h2>
<p class="p1"><span class="s1"> </span></p>
<h2 style="margin: 0.0px 0.0px 14.9px 0.0px; font: 18.0px Times; color: #000000; -webkit-text-stroke: #000000"><span class="s1"><b>2024/09/03</b></span></h2>
<p class="p1"><span class="s1"><span class="Apple-converted-space"> </span></span></p>
<p class="p1"><span class="s1">


<p>This post is about using data to detect bias in systems that allocate public resources.</p>
<p>For example, in the US there are approximately 90,000 people waiting for a kidney transplant.
<!-- In 2023, approximately 21,000 people received a transplant from a deceased donor, but 44,000 people were added to the list (all data from [OPTN](https://optn.transplant.hrsa.gov/data/), accessed September 2024).
-->
When kidneys from a deceased donor become available, the Organ Procurement and Optimization Network (OPTN) must decide which of these waiting patients to make offers to.
As another example, in Hennepin County there are currently around 1,000 homeless single adults on a priority list waiting for housing assistance. When housing providers have openings, they contact the county’s “Coordinated Entry” system, which “refers” individuals from its priority list to the providers.</p>
<p>In these applications, it is important to assess whether the prioritization and offer policy is biased towards or against particular groups – especially for protected classes such as race and gender. However, defining and detecting bias are both difficult, for many reasons.</p>
<p>In this post, I will focus on one reason (survivorship bias) that detecting bias can be difficult. I will say a system is “biased” against a group if that group gets worse outcomes than it would under random allocation. I am <em>not</em> saying that this is necessarily the right definition of bias – that is a topic for a different post. But at the very least, this definition is natural and succinct, and turns the nebulous question of “Is the system biased?” to the seemingly more straightforward “If we changed to allocating resources randomly, which groups would be helped and which would be hurt?”</p>
<div id="a-simple-example" class="section level1">
<h1>A Simple Example</h1>
<p>I will consider an agency that operates as follows. For each individual that requests assistance, the agency calculates a “score” based on various attributes of that individual. When resources become available, they are offered to applicants with the highest scores.</p>
<p>This agency comes to you to do analysis. They give you the list of all individuals waiting for assistance (including the attributes needed to calculate each individual’s score), and ask a very straightforward question: does their scoring system tend to give higher scores to men or to women? And which group would benefit from a switch to a lottery system that simply allocated resources at random?</p>
<p>You are no stranger to spreadsheets, and quickly calculate the averages for both groups. Women have an average score of 1.5 out of 3, while men have an average score of 1. Digging deeper, you find that almost all of the highest-scoring people on the list are women. You calculate the <span class="math inline">\(p\)</span>-values associated with these findings, and get that both findings are highly statistically significant (<span class="math inline">\(p&lt;.001\)</span>). What can you conclude?</p>
<p>It’s natural to say that because women have significantly higher scores than men, and most top positions on the list are held by women, moving to a lottery system would most likely benefit men. However, this may not be correct! The reason for caution is that you are only looking at people who have not yet received assistance, who are not representative of the full set of applicants. This is sometimes referred to as “survivorship bias.”</p>
<p>To illustrate this idea, suppose that each month, 100 new applicants arrive, half men and half women. Men are equally likely to score 1 or 3. Women are equally likely to score 1 or 2. Each month, you can assist 25 people. Generally, these will almost all be men with a score of 3. This means that the remaining list will consist of women who score 2, women who score 1, and men who score 1. As a result, the women on the list have an average score of 1.5, versus 1 for the men, and almost all of the top spots on the list at any moment in time are held by women. Yet, if we look at <em>all</em> arrivals, we see that men actually receive higher scores (an average of 2 instead of 1.5) and almost all assistance currently goes to men! Switching to random allocation in this case would actually help women substantially.</p>
</div>
<div id="simulations" class="section level1">
<h1>Simulations</h1>
<p>The example above was very stylized to make the idea clear, but this effect arises in settings that feel much less artificial. The following code simulates an arrival process in which men and women are equally likely to arrive requesting help. There are only enough resources to help approximately 1/4 of all clients. Resources must be allocated immediately, and are always given to the waiting client with the highest score. Men’s and women’s are both normally distributed with a mean of 6, but the standard deviation of men’s scores is 3, and the standard deviation for women is 1.</p>
<pre class="r"><code>sample_types = function(n,t,d){
	arrival_times = sort(runif(n,min=0,max=t))
	departure_times = arrival_times + rexp(n)/d
	gender = sample(c(&#39;M&#39;,&#39;W&#39;),n,replace=TRUE) #Half men, half women 
	men_score_dist = function(n){return(rnorm(n,mean=6,sd=3))} #Men have avg score 6, sd of 3
	women_score_dist = function(n){return(rnorm(n,mean=6,sd=1))} #Women have avg score 6, sd of 1
	score = men_score_dist(n)*(gender==&#39;M&#39;)+women_score_dist(n)*(gender==&#39;W&#39;)
	return(list(gender=gender,score=score,arrival_times=arrival_times,departure_times=departure_times))
}

#Prioritize clients by score (resources must be used immediately)
determine_outcomes = function(clients,resource_arrival_times){
	match_time = rep(NA,length(clients$arrival_times))
	for(i in 1:length(resource_arrival_times)){
		waiting_clients = which((clients$arrival_times&lt;resource_arrival_times[i]) &amp; (clients$departure_times &gt; resource_arrival_times[i]) &amp; (is.na(match_time)))
		if(length(waiting_clients)&gt;0){
			scores = clients$score[waiting_clients]
			j = waiting_clients[which(scores==max(scores))]
			match_time[j] = resource_arrival_times[i]
		}
	}	
	return(match_time)
}

#Given data, find the average outcome for different groups
avg_outcome = function(outcome,groups,who,data){
	return(tapply(data[[outcome]][who],data[[groups]][who],mean))
}

set.seed(123)
t = 10000 #time at which we examine the list
lambda = 1 #client arrival rate
mu = 1/4 #resource arrival rate
d = 0.001 #client departure rate
N = rpois(1,t*lambda) #Number of client arrivals in [0,t]
R = rpois(1,t*mu) #Number of resource arrivals in [0,t]
clients =  sample_types(N,t,d) #Generating client data base
resource_arrival_times = sort(runif(R,min=0,max=t))
match_time = determine_outcomes(clients,resource_arrival_times)

matched = which(!is.na(match_time)) #Identifying clients that have been matched
remaining = which(is.na(match_time)&amp;(clients$departure_times&gt;t)) #Identifying clients that remain in pool

avg_outcome(&#39;score&#39;,&#39;gender&#39;,1:N,clients) #Avg score of all clients, split by gender</code></pre>
<pre><code>##        M        W 
## 6.035184 5.986527</code></pre>
<pre class="r"><code>table(clients$gender[matched]) #Number of matched clients of each gender</code></pre>
<pre><code>## 
##    M    W 
## 1823  736</code></pre>
<pre class="r"><code>avg_outcome(&#39;score&#39;,&#39;gender&#39;,matched,clients) #Avg score of matched clients, split by gender</code></pre>
<pre><code>##        M        W 
## 9.161122 7.546093</code></pre>
<pre class="r"><code>table(clients$gender[remaining]) #Number of remaining clients of each gender</code></pre>
<pre><code>## 
##   M   W 
## 302 380</code></pre>
<pre class="r"><code>avg_outcome(outcome=&#39;score&#39;,groups=&#39;gender&#39;,who=remaining,data = clients) #Avg score of remaining clients, split by gender</code></pre>
<pre><code>##        M        W 
## 4.062938 5.700151</code></pre>
<!--
plot_test(clients$gender[remaining],rank(-clients$score[remaining]),plot_title='')
-->
<p>In this example, when the simulation ends there are 682 clients remaining on the list: 302 men, and 380 women. In this group, men have an average score of 4.1, and women an average score of 5.7. This is a significant difference! If you look at the top 100 spots on the list, 74 are occupied by women. In other words, looking at the list of clients waiting for help makes it look like the system is biased against men.</p>
<p>And yet, if we look at who has been helped by the system, we see 1823 men and only 736 women! So clearly, the system is biased against women!</p>
<p>On the other hand, if we looked at average scores given to each group (which is a common approach in practice), we would see that both are right around 6, as expected. So we might conclude that there is no bias either way.</p>
</div>
<div id="closing-remarks" class="section level1">
<h1>Closing Remarks</h1>
<p>Defining and detecting bias is difficult. This topic is no longer purely hypothetical to me, as I have begun working with several organizations to help with assessing their prioritization and allocation policies.</p>
<p>In this post, I gave one simple definition of bias, and identified that depending on which statistics you choose, the system could look biased against women, biased against men, or fair. While I have long been aware of survivorship bias, writing this post made me think I previously under-estimated how easily survivorship bias can cause seemingly natural analysis to point to the wrong conclusion. I hope that the examples in this post make this idea clear.</p>
<p>One take-away I have is that if someone wants find bias, they can almost always support their accusation with a seemingly damning statistic. This tells me that policymakers should not merely react to criticism and negative press, but must be proactive about how to define and detect bias. That way, they will hopefully identify and improve biased systems, and be prepared to defend well-designed systems against spurious accusations.</p>
</div>
<span class="Apple-converted-space"> </span></span></p>
<p class="p1"><span class="s1">  <footer>
  <script src="//yihui.name/js/math-code.js"></script>
<script async src="//mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML"></script>

<script async src="//yihui.name/js/center-img.js"></script>

<div id="commento"></div>
<script src="https://cdn.commento.io/js/commento.js"></script>


<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-152747471-1', 'auto');
	
	ga('send', 'pageview');
}
</script>
  
  <hr/>
  © <a href="https://nickarnosti.com">Nick Arnosti</a> 2023
  
  </footer>
  </body>
</html><span class="Apple-converted-space"> </span></span></p>
<p class="p4"><span class="s1"></span><br></p>
<p class="p5"><span class="s1"></span></p>
</body>
</html>
