---
title: 'Have you made the process faster?'
date: '2020-02-04'
author: Nick Arnosti
tags:
  
categories:
  Operations
draft: true
---


Suppose you go to visit the doctor. You arrive, and are asked to fill out a ream of paperwork. Then you wait in the lobby until your name is called. At that point, you're brought to a room, where you see a nurse for some tests, before waiting for the doctor to see you. 

The paperwork part of this process has always struck me as especially antiquated. Not only does it take a lot of my time, but then the receptionist has to copy this information into their online system! If I could enter the information digially, the receptionist wouldn't need to copy it. Additionally the system could take information from one form and use it to populate others, reducing the time I spend supplying information.

The question for the day: if I make these changes, have we made the system faster?

It turns out, the word "faster" is pretty slippery. The question above could be interpreted in multiple ways. It could mean, "Will this change reduce the amount of time that patients spend at the office?" In operations, we would ask whether the **throughput time** will be reduced. 

Alternatively, we might be asking "Will this change allow the office to see more patients?" In class, we would ask whether the **capacity** of the office has increased.

It's possible that the answer to the first question is 'yes'

