---
title: 'Kidney Chain Matching'
date: '2022-04-17'
author: Nick Arnosti
draft: true
---

A [recent post]() noted that approximate solutions to a problem can offer more insights than their more complex exact alternatives. This post will explore this idea in a very different setting. 

**The problem is as follows.** There is a directed graph Erdos Renyi graph on $n$ nodes: each of the possible $n(n-1)$ edges is present with some probability $p \in (0,1)$, independently of all other edges.^[This random graph model has been used to model many settings. Most relevantly to my work, it has been used to model kidney exchange. In this context, each node represents a pair of people: a patient in need of a kidney, and a donor who is willing to give up a kidney but is medically incompatible with their patient. An edge between nodes $i$ and $i'$ indicates that the donor of $i$ can give to the patient of $i'$, and a path from $s$ to $t$ indicates that if $s$ is an "altruistic donor" with no intended recipient, a chain can be started from $s$ that will result in the patient of $t$ receiving a kidney. But this point is purely about math, so I will leave it at that. ] 

1. Given a fixed starting node $s$ and target node $t$, what is the probability that there exists a path from $s$ to $t$?
2. If we start with only $s$ and $t$ and add nodes (and their associated edges) one at a time, on average how many nodes must be added before a path between $s$ and $t$ appears?

The answer to the second question follows immediately from the first: if we let $q(n,p)$ be the answer to the first question, then the expected size of the graph when a path from $s$ to $t$ first emerges is $\sum_{n \ge 0} (1 - q(n,p))$.

In this post, I will first present an exact solution using dynamic programming, and then present a simple and insightful approximation. In particular, I demonstrate that the answer to the second question is approximately $2/p$.

# Dynamic Programming Solution

One challenge to answering these questions is that there are a huge number of possible graphs. However, we can solve this problem using dynamic programming. That is, solve for small values of $n$ first, and then use that solution to solve for larger values of $n$.

For any integers $k \le n$, let $P[n,k]$ denote the probability that in a random graph with $n$ nodes, the number of nodes that can be reached from $s$ (including $s$ itself) is equal to $k$. It is clear that $P[1,1] = 1$, and that $P[2,2] = p = 1- P[2,1]$. In general, I claim that we can calculate entries in $P$ according to the following recursive formula: 

$$P[n,k] = P[n-1,k]\times (1-p)^{k}+\sum_{j = 1}^{k-1}P[n-1,j]\times(1-(1-p)^{j})\times P[n-j,k-j].$$

To see this, imagine growing the graph one node at a time. We wish to calculate $P[n,k]$ -- the probability that when we have $n$ nodes, $k$ are reachable. This can only occur if, at $n-1$ nodes, some number $j \le k$ are reachable. The above expression sums, across possible values of $j$, the probability of having $j$ reachable nodes in a graph of size $n-1$, times the probability that adding a new node increases the size of the reachable set by exactly $k-j$.

The first term in the sum represents the $j = k$ case. In this case, the newly-added node $w$ must not have an incoming edge from any of the previously reachable nodes (this occurs with probability $(1-p)^k$). If $j < k$, then $w$ must have an incoming edge from at least one reachable node, and in addition, reach the correct number of previously unreachable nodes. The first of these events occurs with probability $(1 - (1-p)^j)$, while the second occurs with probability $P[n-j,k-j]$. This latter claim holds because learning that the set of unreachable nodes is $U$ does not tell us anything about edges *within* $U$, so we can treat $U \cup {w}$ as a "fresh" graph, with $w$ playing the role of $s$.

The following code plots the distribution of the number of reachable nodes, when $n = 100$ and $p = 0.02$. One interesting observation is that this distribution is bimodal: it is likely that $s$ is either connected to few nodes, or a majority of them.
```{r, echo=TRUE}
probability_table = function(N,p){
	P = matrix(0,N,N) #P[n,k] = probability that in a network with a total of n nodes (including s), k are connected (including s)
	P[1,1] = 1
	for(n in 2:N) for(k in 1:n){
		P[n,k] = P[n-1,k]*(1-p)^k
		if(k > 1) for(j in 1:(k-1)) P[n,k] = P[n,k]+P[n-1,j]*(1-(1-p)^j)*P[n-j,k-j]
	}
	return(P)
}
N = 100
p = .02
plot(c(1:N),probability_table(N,p)[N,],las=1,xlab='Reachable Vertices',ylab='Probability')
```

Once we know the values of $P$, we can easily answer our original questions. Since nothing distinguishes our target node $t$ from any other, if from $s$ we can reach $k-1$ of the other $n-1$ nodes, the probability that $t$ is one of these nodes is $(k-1)/(n-1)$. Summing across values of $k$, we get that the probability of a path from $s$ to $t$ is $\sum_{k = 1}^{n} P[n,k]\times (k-1)/(n-1)$. The following code uses this fact to plot the probability of a path from $s$ to $t$ as a function of the number of nodes, fixing $p = 0.1$.

```
path_probability = function(N,p){
  P = probability_table(N,p)
  return((P[,]%*%(1:N)-1)/(1:N-1))
}
plot(1:50,path_probability(50,.1),xlim=c(0,50),ylim=c(0,1),xlab='n x p',ylab='Probability of path from s to t',las=1)
```

```
p = 0.1
points(2:50,1 - (1-p)^(2:50-1),pch='x')
points(2:50,p+(1-p)*(1 - (1-p^2)^(2:50-2)),pch='x')
```

We can also add lines for other values of $p$. Of course, the smaller $p$ is, the larger $n$ needs to be to have a reasonable chance of success. To put curves for different values of $p$ on a similar scale, I normalize the $x$-axis to be $n \times p$ (which is approximately the average degree of each node), rather than simply $n$. Let's add a line in green for $p = 2.5\%$, and a line in red for $p = 1\%$.
```
plot_probability = function(N,p,color){
  points(1:N*p,path_probability(N,p),pch='.',cex=3,col=color)
}
plot(NULL,cex=3,xlim=c(0,5),ylim=c(0,1),xlab='n x p',ylab='Probability of path from s to t',las=1)
plot_probability(5/.1,.1,'blue')
plot_probability(5/.025,.025,'green')
plot_probability(5/.01,.01,'red')
```

# Simpler Approximations

The dynamic programming formulation above is somewhat clever (and certainly more involved than the example in my previous post). However, like other dynamic programming solutions, it does not necessarily lend a lot of qualitative insight about how the probability of a path depends on $n$ and $p$. Additionally, it gets slow for small values of $p$, since we need to study ever-larger values of $n$, and it runs in $\mathcal{O}(n^3)$ time.









I claim that for small $p$, the number of nodes required to have a success probability of $y$ is approximately $\frac{-log(1-\sqrt{y})}{p\sqrt{y}}$. We can add this approximation to our graph.
```
y = c(1:100)/101
lines(-log(1-sqrt(y))/sqrt(y),y,lwd=3)
```

We can use simple arguments to get upper bounds on the probability of a path (and lower bounds on the expected waiting time). For example, the probability of such a path is at most the probability that there is an outgoing edge from $s$, which is $1 - (1-p)^(n-1)$. We can get a better bound by noting that for there to be a path from $s$ to $t$, $s$ must have an outgoing edge *and* $t$ must have an incoming edge. The probability of both of these events occurring in a graph of total size $n$ is
$$\mathbb{P}(\text{path from } s \text{ to } t) \le  \mathbb{P}(s \text{ has an outgoing edge } {and} \, t \text{ has an incoming edge}) =   p + (1-p)\times(1-(1-p)^{n-2})^2.$$


The expected size of the graph when $s$ gains its first outgoing edge is $1/p+1$. Similarly, the expected size of the graph when $t$ contains its first incoming edge is $1/p+1$. Thus, this is a clear lower bound on the answer to our second question. 




```
expected_size = Vectorize(function(p){
  N = ceiling(6/p)
  return(2+sum(1-path_probability(N,p)[-1]))
})
plot(expected_size,xlim=c(.01,0.5),xlab='p',ylab='',las=1)
```






After a little work, this tells us that the expected time until both of these conditions are met is approximately $1.5/p$.^[For those familiar with exponential random variables, one intuition for this is as follows. Let $V$ be the set of nodes other than $s$ and $t$. Then the time until there is an edge from $s$ to some node in $V$ and the time until there is an edge from some node in $V$ to $t$ are independent geometric random variables. If $p$ is small, these random variables can be well-approximated by continuous-valued exponential random variables. The expected maximum of two independent exponential random variables, each with mean $1/p$, is well-known to be $1.5/p$.]

Meanwhile, we can get a simple lower bound on the probability of a path from $s$ to $t$ by considering paths of length two. With each new node $w$, the chance of a path of length two through $w$ is $p^2$. Therefore, the probability of a path from $s$ to $t$ is at least $1-(1-p^2)^(n-2)$ and the expected number of nodes before such a path emerges is at most $1/p^2 + 2$. 

# Approximate Solution

The aforementioned upper and lower bounds are simple, but there is a big gap between them! Another approach to getting approximate answers is to consider a limiting regime where $p \rightarrow 0$.

Although our problem involves a directed graph, we can actually simplify slightly by considering an undirected graph. This is because we wish to calculate the number of nodes that can be reached from $s$. For any other nodes $i$ and $j$, imagine waiting to reveal whether there are edges between them until one of them can be reached from $s$. At this point, we only care whether there is an edge from the reachable node to the previously unreachable one; the reverse edge will never affect the reachable set. In other words, only the result of the "first" coin flip between each pair of nodes is relevant. 

So our questions can be rephrased as follows. If we have an ER random graph with each edge present with probability $p$, how likely is it that a specific source vertex is connected to a specific sink vertex? On average, many vertices are needed before these vertices are connected?

Well-known results on asymptotic Erdos-Renyi random graphs say that if $np<1$, then all components have size $O(\log(n))$, so the probability that any two specific nodes are connected is vanishingly small. If $np = \lambda > 1$, then it is known that there is one large connected component involving a constant fraction of all nodes (and all other connected components are of size $O(\log(n))$). We want to analyze the size of this large component.

Suppose that this component involves a fraction $q(\lambda)$ of all nodes. We can estimate the probability that a particular node $t$ is not part of this component in two ways. First, this probability should equal $1-q$, because there is nothing special about $t$. Second, it should equal the probability none of the nodes with edges into $t$ are in this component. If $p$ is small, then the number of nodes with edges into $t$ is well-approximated by a Poisson random variable with mean $\lambda = np$. Each of these nodes is in the large component with probability $q$, and in a large graph, these events are approximately independent. Thus, the probability that none of the nodes with edges into $t$ are in the large component is approximately $e^{-\lambda q}$. This gives us the equation 
$$1 - q(\lambda) = e^{-\lambda q(\lambda)}.$$
If $\lambda \le 1$, the only solution is $q(\lambda) = 0$. If $\lambda > 1$, there is a 


Suppose that we add $t$ last. The number of nodes with incoming edges to $t$ follows a binomial distribution. The node $t$ is reachable from $s$ if and only if one of these nodes with incoming edges is reachable from $s$.






Use the following heuristic reasoning. Suppose that our target node is reachable with probability $q(\lambda)$. The number of nodes connected to our target is approximately Poisson with mean $\lambda$. Each of these nodes is identical to our target node, so each must also be reachable with probability $q(\lambda)$. Our target node is reachable if and only if one of its neighbors is reachable. If we assume independence of reachability across these nodes, we get the following equation for $q(\lambda)$:

Let $X$ be a non-negative random variable with CDF $F$. Then 
$$\mathbb{E}[X] = \int_0^\infty (1 - F(x))dx$$
If $F$ is invertable, then
$$\int_0^\infty (1 - F(x))dx = \int_{x = 0}^\infty \int_{y = F(x)}^1 dy dx = \int_{y = 0}^1 \int_{x = 0}^{F^{-1}(y)} dx dy = \int_{0}^1 F^{-1}(y) dy.$$

$$\hat{F}^{-1}(y) = \frac{-\log(1 - \sqrt{y})}{\sqrt{y}}$$
\[\int_0^1 -\log(1 - \sqrt{y})/\sqrt{y} \,\, dy = 2.\]








Note that for $\lambda \le 1$, the only solution is $q = 0$, and for $\lambda > 0$, there is exactly one non-zero solution $q \in (0,1)$. This is our approximation of the answer to our first question. The answer to our second question is then

\[\int_0^\infty (1 - q(\lambda)^2)d\lambda = 1 + \int_1^\infty (1 - q(\lambda)^2)d\lambda. \]


The taylor expansion for $-\log(1-x)/x$ is $\sum_{k = 0}^{\infty} x^k/(k+1)$, so
\[-\int_0^1 \log(1-\sqrt{y})/\sqrt{y}\,\, dy = \int_0^1 \sum_{k = 0}^{\infty} \frac{y^{k/2}}{k+1} dy = \sum_{k = 0}^\infty \frac{2}{(k+1)(k+2)} = 2,\]
where the final equality follows from noting that $\frac{2}{(k+1)(k+2)} = \frac{2}{k+1}-\frac{2}{k+2}$ and therefore we have a telescoping sum. This suggests that on average we need $np \approx 2$ before there is a path from $s$ to $t$.
