---
title: 'The Prophet Secretary Problem'
date: '2020-10-09'
author: Nick Arnosti
tags:
  Prophet Inequalities
categories:
  Pseudo-Research
draft: true
nurmarkdownumber_sections: true
---
\newcommand{\bF}{\bf F}

One of the advantages of the clean analysis is that it is relatively straightforward to generalize.

#The Prophet Secretary Problem

In order to get a better performance guarantee, we need to increase expected demand (lower the threshold $t$). The risk is that by doing so, we increase the chance of missing out on a large value.

Their analysis captured this through $\delta_k(t,\bF)$

$$ \alpha_k(t,\bF) = \mathbb{E}_{V \sim \bF} \left[\frac{\min(1+D_t(V),k)}{1+D_t(V)} \right].$$
Note that $\alpha_k(t,\bF) \geq \delta_k(t,\bF)$, since the ratio inside of the expectation is $1$ whenver $D_t(V) < k$.

```{proposition, label='lb'}
In the random arrival order model, for all $\bF$, $k$, $t$, we have
\[ \frac{ST_k^t(\bF)}{LP_k(\bF)} \geq \min(\alpha_k(t,\bF),\mu_k(t,\bF)).\]
```

To prove this, we fix $t$ and $V$, and define $D^i = {\bf 1}(V_i > t)$, $D = \sum_{i = 1}^n D^i$ and $D^{-i} = D - D^i$. The following identity can be quickly verified by sequentially considering the cases $D < k$ and $D \geq k$: 
\begin{equation} \min(D,k) = \sum_i D^i \frac{\min(1 + D^{-i},k)}{1 + D^{-i}}. 
(\#eq:tricky) \end{equation}

When demand $D$ is at most $k$, then every value above $t$ is selected. When $D$ is above $k$, then each value above $t$ is selected with probability $k/D$. From this observation, we can calculate the performance of any static threshold policy as follows.

\begin{align*}
ST_k^t({\bf F})& = \mathbb{E}\left[\sum_{i = 1}^n  V_i D^i \frac{\min(1+D^{-i},k)}{1+D^{-i}} \right] \\
& = \mathbb{E} \left[\sum_{i = 1}^n  \left(tD^i + \max(V_i - t,0) \right) \frac{\min(1+D^{-i},k)}{1+D^{-i}} \right] \\
& = t \cdot \mathbb{E}\left[\sum_{i = 1}^nD^i\frac{\min(1+D^{-i},k)}{1+D^{-i}}\right] + \mathbb{E}  \left[\sum_{i = 1}^n   \max(V_i - t,0) \frac{\min(1+D^{-i},k)}{1+D^{-i}} \right] \\
& = t \cdot  \mathbb{E}\left[ \min(D,k)\right] + \sum_{i = 1}^n \mathbb{E}  \left[  \max(V_i - t,0) \right] \mathbb{E} \left[ \frac{\min(1+D_t^{-i}(V),k)}{1+D_t^{-i}(V)} \right] \\
& \geq t \cdot  \mathbb{E}\left[ \min(D,k)\right] + \sum_{i = 1}^n \mathbb{E}  \left[  \max(V_i - t,0)  \right] \alpha_k(t,{\bf F}) \\
& = t \cdot k \cdot \mu_k(t,{\bf F}) + U(t,{\bf F}) \alpha_k(t,{\bf F}).
\end{align*}

We established in a previous post that the performance of the LP relaxation is at most $t \cdot k + U(t,\bF)$, from which Proposition \@ref(prp:lb) follows.

Note that $\mu_k$ is decreasing in $t$, and $\alpha_k$ is decreasing. This suggests a natural algorithm: choose a threshold $t^M$ such that $\mu_k(t,\bF) = \alpha_k(t,\bF)$. We will also consider an even simpler algorithm: choose threshold $t^{LP}$. Call these algorithms $A^M$ and $A^{LP}$, respectively. We start by analyzing $A^{LP}$. 

```{lemma}
For all $k, \bF$, we have $\mu_k(t^{LP},\bF) \geq \alpha_k(t^{LP},\bF)$.
```

```{proof}
By \@ref(eq:tricky), we have
\begin{align*}
k \cdot \mu_k(t,{\bf F}) & = \mathbb{E}\left[ \sum_i D^i \frac{\min(1+D^{-i},k)}{1+D^{-i}} \right] \\
& =  \sum_i \mathbb{E}[D^i] \mathbb{E}\left[ \frac{\min(1+D^{-i},k)}{1+D^{-i}}\right] \\
& \geq  \sum_i \mathbb{E}[D^i]  \mathbb{E} \left[ \frac{\min(1+D,k)}{1+D}\right] \\
& = \sum_i (1 -F_i(t)) \alpha_k(t,{\bf F}).
\end{align*}
Therefore, when we choose $t = t^{LP}$, we have $\sum_i (1 -F_i(t)) = k$ and $\mu_k \geq \alpha_k$. 
```

From this, we conclude that the competitive ratio of algorithm $A^{LP}$ is at least
\begin{align*}
\min & \mathbb{E}[\min(1,k/(1+D))] \\
s.t. & D = \sum_i D^{i} \\
& D^i \sim Ber(p_i) \\
& \sum_i p_i = k.
\end{align*}

A result of Hoeffding (1956) implies that there is an optimal solution where each $p_i$ takes on one of three values, two of which are $0$ and $1$. In other words, every non-degenerate $D^i$ has equal $p_i$. Thus, we can search over a two-dimensional family (number of $i$ with $p_i= 1$, number of $i$ with $0 < p_i < 1$). The following code does this.

```{r}
#Looking for minimum (or maxmimum) of E[f(N)], when N is sum of independent bernoullis.
#By Hoeffding (1956), can reduce to two-parameter search (all probs that are not 0 or 1 are equal)
compute_value = function(f){
	return(Vectorize(function(lambda,k,n_ones,n_others){
		if(n_ones > lambda){ print("ERROR: INFEASIBLE (n_ones too large)"); return(NA)} #must have n_ones <= lambda 
		if(n_ones+n_others < lambda) {print("ERROR: INFEASIBLE (n_others too small)");  return(NA)} #Can't spread lambda mass among so few
		if(n_others == 0){ return(f(n_ones))}
		N = c(0:n_others)
		p = (lambda-n_ones)/n_others #probability of success for "others" 
		return(sum(dbinom(N,n_others,p)*f(N+n_ones)))
	}))
}
alpha = Vectorize(function(N){return(min(1,k/(1+N)))})
mu = Vectorize(function(N){return(min(1,N/k))})
k = 2
lambda = k
n_ones = c(0:floor(lambda))
n_total = ceiling(lambda) + c(0:10)
A = matrix(1,nrow=length(n_ones),ncol=length(n_total)) #A[i,j] will give \alpha with n_ones[i] ones and n_total[j] - n_ones[i] others
M = matrix(1,nrow=length(n_ones),ncol=length(n_total)) #M[i,j] will give \alpha with n_ones[i] ones and n_total[j] - n_ones[i] others
for(i in 1:length(n_ones)){
	A[i,] = compute_value(alpha)(lambda,k,n_ones[i],n_total-n_ones[i]) 
	M[i,] = compute_value(mu)(lambda,k,n_ones[i],n_total-n_ones[i]) 
}
pmin(A,M)
```

For $k \geq 5$, it appears that the worst case is when there are no variables with $p_i = 1$, and many variables with $0 < p_i < 1$. For smaller $k$, the worst case of this optimization problem involves some variables with $p_i = 1$. For example, with $k = 1$ the worst case is $1/2$, and with $k = 2$ it is $2/3$. These observations lead to the following conjecture.

```{conjecture}
For $k \geq 5$, algorithm $A^{LP}$ offers a guarantee of $\mathbb{E}[\min(P^{k},k)]/k$.

For $k < 5$, algorithm $A^{LP}$ offers a guarantee of $k/(k+1)$.
```

How about our original algorithm? Based on playing around with small $k$, I conjecture the following.

```{conjecture}
Algorithm $A^M$ offers performance guarantee of $\mathbb{E}[\min(P^{k},k)]/k$
```

Unfortunately, here we can't immediately apply the results of Hoeffding (1956).

