---
title: 'Predicting Outcomes in Random Matching Markets'
date: '2024-11-08'
author: Nick Arnosti
tags:
  School Choice
draft: true
---


Suppose you have $N_{students}$ students and $N_{schools}$ schools. 

Each school has capacity $C$, and each student lists $\ell$ schools in a uniformly random order.


This model was first studied by Pittel, in the case where $N_{students} = N_{schools} = \ell$. In that case, there is a large core. Then Roth and Peranson proposed $N_{students} = N_{schools} > \ell$. More recently, Ashlagi Kanoria and Leshno analyze the case $m \ne n = \ell$, and found something surprising.

This post is on a surprisingly simple and accurate approximation to these outcomes. This comes from my paper "Lottery Design for School Choice."


\begin{equation} N_{students}(1-(1-P(\lambda))^\ell) = N_{schools} \mathcal{E}(\lambda).\label(balance) \end{equation}
where
\begin{align}
\mathcal{E}(\lambda) & = 1 - e^{-\lambda}\\
\mathcal{P}(\lambda) & = \mathcal{E}(\lambda)/\lambda
\end{align}

Then the fraction of students who get their $k^{th}$ choice is 
\begin{equation}F_k = P(\lambda) (1-P(\lambda))^{k-1}.  \end{equation}

What insights do we get out of this? Can I make it simple?

Now, suppose students list different numbers of schools: student list lengths are drawn iid from some distribution $\mathcal{D}$. Then \@(eq:balance) becomes

\begin{equation} N_{students} \color{red}{\mathbb{E}_{\ell \sim \mathcal{D}}[}1-(1-P(\lambda))^\ell\color{red}{]} = N_{schools} \mathcal{E}(\lambda).\end{equation}

Meanwhile the fraction of students who list at least $k$ schools and get their $k^{th}$ choice is 
\begin{equation}F_k = \color{red}{\mathbb{P}_{\ell \sim \mathcal{D}}(\ell \ge k)} P(\lambda) (1-P(\lambda))^{k-1}.  \end{equation}



Now suppose we want schools to have more than one seat. Say, they each have $C_h$ seats. Then we simply re-define the enrollment function 

\begin{equation} \mathcal{E}(\lambda) = \color{red}{\mathbb{E}[\min(Pois(\lambda),C)]} \end{equation}


Now suppose we want schools to have different capacities. Potentially, they are not all equally popular, either: suppose that each school $h$ has a "weight" $w_h$ which represents its popularity relative to the average school, so $\sum_h w_h = N_{schools}$. (This popularity model was used by Immorlica Mahdian, Kojima Pathak, some Ashlagi papers and more). 

\begin{equation}
\mathcal{E}(\lambda) = \mathbb{E}[\frac{1}{N_{schools}}\sum_{h} \color{red}{w_h}\min(Pois(\color{red}{w_h}\lambda),C_\color{red}{h})]
\end{equation}

The uniform case corresponds to taking $w_h = 1$ for all $h$.


In my paper, I show that these approximations are actually valid in the limit as $\mathcal{D}$ is fixed and $N_{students}$ and $N_{schools}$ grow in a fixed ratio.

I also give analogous expressions for the case where school priorities are identical (rather than uniformly random). I use these expressions to show various insights (give examples -- reproduce Ashlagi Kanoria Leshno, or Marx Schummer?). Check it out!


