---
title: "What I Read and Listened to This Week (1/12/2026)"
author: "Nick Arnosti"
date: '2026-01-16'
output: html
draft: true
---

Like a lot of other people I know, I spend a lot of time browsing articles online, scrolling through social media, watching YouTube videos, and listening to podcasts. This post is going to share a lot of what I read and listened to in the past week, and include reflections on this content.

My goals in sharing this are the following:

1. *Synthesis.* I often feel like information flows in front of my eyes without ever really making it into my brain. Scrolling through articles can be mindless, and not very intentional. My hope is that by forcing myself to reflect, I will retain more information and have more original thoughts.

2. *Deterrence.* I want to spend less time passively scrolling. Forcing myself to reflect on what I read or listen to serves as a sort of tax on this activity that can hopefully reduce it.

3. *Awareness.* What we see and hear influences how we think. Just as it is good to be aware of what foods we are putting into our bodies, it is good to be aware of what messages we are putting into our minds (especially in the era of algorithmic feeds). This is a first step to making me more aware of my own consumption patterns.

That said, somewhat scary to share. Could be judged for what I am consuming, or how I am processing it. Note that a goal of this is **not** to provide an unbiased or comprehensive take. I won't try to fully summarize an article. Instead, I will focus on what I found interesting or memorable about it. (However, this could serve to point you to articles.)



What I read and thought this week

January 12

Yes Theory: 72 Hours Lost in the World’s Richest Dictatorship (no hotel, no food, no transportation...)

They are sent to Brunei, driven to a rural location, and given 72 hours to get back to the capital while achieving as many as possible of the following:

Do not pay for transport at any point
Stay at a local’s house
Work a local job for at least 1 hour
Have a local show you a beautiful hidden scenic place
Eat a local meal you are scared of trying
Attend a local event
Make a local friend
Explore a historical sight and learn something new
Take 10 selfies with strangers
Attend a sapak takraw training 
Learn a sentence in the local language
Cook a Bruneian dish with a local
Join evening prayers at a mosque
Go on a side quest with a stranger

I could quibble with the fact that some of these goals are pretty subjective (“make a friend” or “go on a side quest”), but overall I love this approach to travel. They end up staying with a family for three nights, who shows them local places and teaches them to cook local dishes. This experience is enabled by the fact that the family speaks English. 

My key takeaway is that authentic and spontaneous connection is often available in rural areas if you look for it (and are willing to put yourself out there).

Andrew Gelman blogs titled “The Soft Bigotry of Low Expectations” and “8 arguments against polling”. The first was uninteresting (about RFK’s revised food pyramid) while the second was long and I only skimmed it.

Jerusalem Demsas on the Argument: Karine Jean Pierre is not a #Girlboss https://www.theargumentmag.com/p/karine-jean-pierre-is-not-a-girlboss

Matt Yglesias on the Argument: The Fox in Liberalism’s Henhouse

Matt Yglesias and Jerusalem Demsas podcast: What Went Wrong with Modern Liberalism https://www.theargumentmag.com/p/what-went-wrong-with-modern-liberalism (Also available as podcast on Spotify)

I cluster these three together because they are all broadly critical of the movement to define identity through race, sexuality, and other group identifiers.

My main take-aways from the KJP article: 
1. The point of diversity among people in power is to produce better outcomes (not just diversity for its own sake). 
2. KJP seemed unprepared, and overly concerned with her “identity.”

In my opinion, the first thesis is reasonable, but not obvious. Some might say just having a black person in role X will inspire children to see themselves differently. Also a little strange to implicitly say “people will look out for interests of those similar to them” (though of course this is likely true). Perhaps a nicer framing is “people will be aware of challenges facing those similar to them, and try to address these.” 

My main take-away from the Fox in the Henhouse article: we can choose to think and speak in terms of individuals or groups. Many on the left have become obsessed with group identity. I think this is the wrong approach.

As for the podcast, I didn’t get through the entire thing and won’t seek to be comprehensive.

A key quote that I agree with:

“You are also creating reality” [with your choice of language].
“The more that you talk about this, the more that group difference is relevant to how people think about themselves.”

She uses the analogy of people who wear glasses vs those that do not. Almost certainly, these groups — on average — differ along many dimensions. However, people don’t think of themselves as glasses-wearers or not. If it started to be a part of everyday conversations, we would start to think of ourselves in this way, and to attribute certain observations to whether we wear glasses.

Put more directly, I think that talking extensively about race doesn’t make race relations better, but rather heightens perceived differences. The following, left in the comment section, also resonated with me:

Jerusalem talks about how all the Asian people she knows who are asked "Where are you from?" are correctly interpreting it as racist. I can't know if this is true. But I think it's likely that by conditioning people to interpret mundane interactions as racist, you are going to get a lot of people seeing far more racism in the world. To avoid conflict, I don't ask people about their backgrounds, even if it's clear they speak English as a second language and didn't grow up in the United States, because I don't want to be accused of implying that they don't belong here. I don't think it's good for society if we are constantly making people fearful of having casual interactions with people of different backgrounds.


A key question that I want to reflect more on: 

When is “statistical discrimination” justified? That is, when is it acceptable to act based on broad group-based observations?


January 13

Following a Twitter post, I came to this summary of data from 2011 on how SNAP recipients spend their money: https://fns-prod.azureedge.us/sites/default/files/ops/SNAPFoodsTypicallyPurchased-Summary.pdf

The striking finding is 9.3% of dollars on sweetened beverages, and another 6.9% on prepared desserts, 5.1% on “candy, juices, sugars, and jams, jellies and preserves”. 

Conservative posters were using these figures to be pretty judgmental of those who receive SNAP benefits. One pointed out that we could simply give out unlimited protein bars, and still avoid hunger. 

I generally believe in offering choices to those receiving benefits. I don’t want to micromanage their diet. I also think that creating programs with strict requirements on what can and can’t be purchased can be confusing to recipients and make the program more costly to administer. But at the same time, soda isn’t even food, and is clearly unhealthy. Do we really want to subsidize soda purchases so heavily? Where do we draw the line? 

Separately, this made me think of an article (or maybe Twitter thread?) I read several weeks ago about people selling their food stamps for, say, 50 cents on the dollar. This seems hard to prevent — even if people have a card with their name on it, they can always buy food for other people in return for cash. It’s also not the worst thing in the world, but it does circumvent some of the purpose of the program. As they say, money is fungible.


Yes Theory on Training with Finnish Soldiers in winter. Mostly they just talk a lot about how cold it is. Boring compared to the Brunei video.

Matt Yglesias “Schools are getting worse in most red states.” 

He points out that although educational outcomes (specifically, fourth grade reading scores) have been improving in Mississippi, Alabama, Louisiana, Tennessee, this is not true of red states more generally. Most of these states — including large ones like Florida and Texas — are following the national trend of falling test scores.

He comments that teachers unions hated No Child Left Behind, but it was somewhat effective. I generally agree with this. Accountability and consequences can definitely be uncomfortable (and I am not claiming that the law was perfect), but without them performance suffers.

A common refrain used by anti-voucher advocates is “No public money without public accountability”. This is reasonable to me! However, as Yglesias points out, then we need to actually have public accountability (for learning outcomes, not just process and procedures). It’s become normal to have most students in a district fail to reach proficiency, and just move on to the next grade anyway.


Against White-Knuckle Parenting, by Kelsey Piper

The main thesis is that parents have a lot of freedom to choose activities (toys, books, instructional classes) that they like, and that suffering through playing with children is not itself virtuous. This feels aligned with a lesson from “Hunt, Gather, Parent” (the only parenting book I have actually read cover-to-cover) not to do lots of kid-centric activities, but rather to include and involve your kids in your life.

A secondary thesis is that boredom/discomfort playing with kids is often an opportunity for personal growth: can we become more curious about what our kids are doing, and how these see the world? Can we feel less guilt about other things we “should” be doing and be more comfortable in the moment? Can we learn to entertain ourselves with interesting thoughts?

In general, my parenting philosophy has often been “whatever makes things easier for us.” I believe that stressed parents are not good for kids, so it’s good for everyone if being around my 2-year-old daughter is not exhausting for me. This means that I never bother washing her pacifier when it falls on the ground. I didn’t (and don’t) follow her closely to ensure she won’t slip or bonk her head on the table. In the house, I let her play out of sight while I read or do household chores. This also helps build her own independence, and it is fun for me to marvel at things she has learned to do on her own.

If anything, I think Kelsey still imposes more rules on what “good parenting” looks like than I would. She says you should read to your kids, take them to the playground, introduce them to art and music, and provide them with toys. These all seem like good things, but none of them feel truly mandatory (of all of these, I do think reading is especially valuable — but that partially reflects cultural values I was raised with). Does “introduce them to art and music” mean some sort of class or outing? I would say (at least at my stage of parenting), it’s enough to play music in the house (that you like) and give them a pen and some paper if they want to scribble on things.

I do feel some sympathy for the perspective of disliking spending time with kids. While I almost always enjoy my first minutes of interaction with my daughter, it is easy to get bored or antsy. Often, kids occupy just enough attention to make it hard to think about or do something else, without being fully engaged. We just had an 18-day stretch with no childcare, and it made me all the more grateful for the ability to leave my daughter with someone else and have time to dedicate to other parts of my identity. I think she’s very cute, but I sometimes feel a little guilty for not wanting to play with her for longer. I agree with Kelsey that this is an opportunity for some personal growth.




A bunch of videos (not really articles) about ICE encounters and activities in the Twin Cities.

This video is taken 3 blocks from my house, the day I returned from vacation (January 11). 

They were apparently patrolling the playground

My personal position is that most immigration is good for the US. I want to open our borders to legal immigrants. I also think that people who are here in an undocumented capacity are generally good for the rest of us (not to mention that they are getting benefits from being able to work and earn money). In other words, I don’t really see the problem that ICE is supposed to solve as a major problem. That said, I totally see how others have different perspectives on this, and the goal of identifying and deporting people who are here without documentation — while not one that I share — at least makes sense to me.

However, there is a question of how to do it, and approaching random people of color demanding to see their papers is definitely not the right way! This makes all of us feel less safe. I’m not personally worried about being confronted because I am white (this is truly one of the more extreme versions of white privilege), but it’s not like I carry my passport with me all the time. The number of federal agents in the twin cities is multiple times the size of the local police force. Our former nanny’s building was raided, and her sister-in-law captured and sent out of state. Before the Trump administration, she was contributing to society by working at a daycare where our friends send their kids, and the kids loved her. Now she is hiding in their house. Similarly, our cleaning people decided to stop their business. There are lots of reports of children — many of whom are likely US citizens due to being born here — not leaving the house to go to school. 

The point is, these encounters absolutely have feel like “guilty until proven innocent”, with no warrants or due process. Even people who are here legally are rationally afraid to go out. This is bad.





Next Post

When is “statistical discrimination” justified? That is, when is it acceptable to act based on broad group-based observations?



Does it have to do with the magnitude of the differences?

A weather forecast might be significantly better than random, but still functionally useless for making decisions. For example: it rains of half of days. The forecast says “likely to rain” on half of days (on 2/3 of these, it rains). It says “likely not to rain” on the other half (on 1/3 of these, it rains). From an individual perspective, how can I use these forecasts? If I want to bring an umbrella whenever the chance of rain is above 20%, then this forecast doesn’t help me make better decisions: with or without it, I end up bringing an umbrella every day.

Going back to the case of fraud in Minnesota, it is certainly true that most of the recently uncovered fraud was perpetuated by Somali immigrants. Nevertheless, most Somalis are not committing fraud, and it’s not a good idea for me (or the state) to act as though they are. Is there some rate of fraud where this would make sense?













Transplants to heavier patients are less likely to succeed. Should we direct transplants to lighter patients? (Clearly not, given we could at least use BMI — just as easy and more predictive.)

One possibility: use predictive model (with lots of features) to predict transplant success.






Older people are much more likely to die from COVID. Should we prioritize them for vaccination? Does the fact that older people are disproportionately white affect the answer?


-Suppose the group is “Member of a particular violent gang.” It seems rational and reasonable for someone to avoid this person, not welcome them into their home, etc. It is still not appropriate for the government to arrest them.
-Suppose the group is “Somali Immigrant”. It is not crazy for the government to say “we don’t want to let more of this group in”, but we should treat those who are here as individuals.



Similarly, it might be true that average IQ differs across racial groups. However, these differences are small compared to variation within each group. Put another way, it’s clearly incorrect to act as though all members of group A are smart and all members of group B are dumb. Even if we care a lot about intelligence, believe it is genetic, and want to encourage more children 

(This feels a little bit icky — could sanitize by making it about height.)

Suppose that we want to increase the average height of our society. Things we could do:
1. Incentivize certain groups to reproduce (or disincentivize others)
2. Ensure adequate nutrition for all children, to help them reach their height potential

Suppose it is found that 



Does it have to do with the strength of signal? 
Let’s say that the measure of strength is arm wrestling. 
“On average, men are stronger than women.” Clearly true.
“Every man is stronger than every woman.” Clearly false.
Yet, if we took a random man and a random woman, and had them arm wrestle, what percentage of the time would the man win? Pretty high.


“On average, group X is higher in characteristic C than group Y”
If I take a random person from group X and a random person from group Y, what is the chance that C is higher for the first than the second?

For C = IQ and X and Y determined by race, not very. For C = strength and X and Y gender, pretty high.


Strength: both a product of genetics and effort (and steroids?)

What should we do about this? Suppose that we have a role — such as a firefighter — that requires physical strength.

Should we say “women cannot be in this role”? I think the answer is clearly not. 
However, it is more reasonable to say “anyone in this role must have certain qualifications — and one of these is strength”. This will definitely have a disparate impact — it makes the role harder for women to get.
What is important is to ensure that the requirement is actually important to the role. If someone said “anyone in this role must have a certain height”, is that truly important? Also, scope narrowly: does the driver of the truck need to be strong?

Challenge: what if “strength” were harder to measure? For example, “anyone we let into the country must have a 80% chance of being employed within 6 months”. How do we assess likelihood of being employed? Through proxies, such as education, gender, wealth? Work visas seem to be a better approach (though they have the downside of reducing employee bargaining power, tying their legal status to their job). Or could let anyone in for 6 months, but kick them out if they haven’t found work in that time.



Reminds me of Cremieux: Affirmative Action justified statistical discrimination. If I don’t trust that same standards are being applied to everyone, forming inferences based on observables makes sense.




Connection to disparate impact law:
1. Plaintiffs demonstrate that there is a disparate impact
2. Defendants explain the purpose of the rule
3. Plaintiffs can show that this purpose can be achieved through other means (with less disparate impact)

Achieved through other means at what cost? Medical example: why downgrade quality of kidneys from black people




Chance of being illegal immigrant (present without documentation) is higher for visibly hispanic people. Does that mean we should stop them on the street?

It’s also higher for people attending a Mexican restaurant. 


Violence is far more likely to be committed by young men than any other demographic. Does that imply we should treat all young men with suspicion?



Is it okay to decide to deport recent Somali immigrants?
To decide not to let new Somali immigrants in?
To decide not to let former Al Qaeda fighters in?


Racial Groups
Ethnic Groups
Young Men



If we had a perfect ability to tell which organs would be successful, use it.
Given we do not, should we use all available information? 

Meaning of statistical discrimination.






What type of group? 

What type of decision? 

How strong is the statistical pattern?



it might be true that “chance of committing welfare fraud”



A child is born with HIV. They cannot ever give blood (or be compensated for it). Not in their control, but reasonable. (Although there is a follow-up: why prevent them from giving blood? Could save for HIV positive patients.


